sudo: false
language: bash
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc

script:
  - ls ./**/*.bats | xargs -I{} bash -c 'cd $(dirname {}) && pwd && bats tests.bats'
